apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      group: shared
  template:
    metadata:
      labels:
        app: nginx
        group: shared
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: deployment-two-index.html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: deployment-two-config